import {contourDensity, geoPath} from "d3";
import {createElement as h, type ReactNode} from "react";
import type {ChannelValue, ChannelValueSpec} from "../channel.js";
import type {Data, MarkOptions} from "../mark.js";
import {Mark as MarkBase} from "../mark.js";
// @ts-expect-error - internal helpers not in .d.ts
import {TypedArray, coerceNumbers, maybeTuple, maybeZ} from "../options.js";
import {applyPosition} from "../projection.js";
// @ts-expect-error - internal helpers not in .d.ts
// prettier-ignore
import {applyFrameAnchor, groupZ} from "../style.js";
import {initializer} from "../transforms/basic.js";
import {channelStyleProps, directStyleProps, indirectStyleProps, transformProp} from "../react/styles.js";
import {withHrefWrap, withTitleChild} from "../react/styles-jsx.js";

// Mark's runtime constructor takes (data, channels, transform, defaults), but the
// public .d.ts declares Mark with a zero-arg constructor; cast for super(...) typing.
const Mark = MarkBase as unknown as new (...args: any[]) => MarkBase;

/** Options for the density mark. */
export interface DensityOptions extends MarkOptions {
  /** The horizontal position channel, typically bound to the *x* scale. */
  x?: ChannelValueSpec;
  /** The vertical position channel, typically bound to the *y* scale. */
  y?: ChannelValueSpec;

  /**
   * An optional ordinal channel for grouping, producing independent contours
   * for each group. If not specified, it defaults to **fill** if a channel, or
   * **stroke** if a channel.
   */
  z?: ChannelValue;

  /**
   * An optional weight channel specifying the relative contribution of each
   * point. If not specified, all points have a constant weight of 1.
   * Non-positive weights are allowed, making associated points repulsive.
   */
  weight?: ChannelValue;

  /**
   * The bandwidth, a number in pixels which defaults to 20, specifies the
   * standard deviation of the Gaussian kernel used for density estimation. A
   * larger value will produce smoother contours.
   */
  bandwidth?: number;

  /**
   * How many contours to produce, and at what density; either a number, by
   * default 20, specifying one more than the number of contours that will be
   * computed at uniformly-spaced intervals between 0 (exclusive) and the
   * maximum density (exclusive); or, an iterable of explicit density values.
   */
  thresholds?: number | Iterable<number>;
}

const defaults = {
  ariaLabel: "density",
  fill: "none",
  stroke: "currentColor",
  strokeMiterlimit: 1
};

/** The density mark. */
export class Density extends Mark {
  z: any;
  constructor(data?: Data, {x, y, z, weight, fill, stroke, ...options}: DensityOptions = {}) {
    // If fill or stroke is specified as “density”, then temporarily treat these
    // as a literal color when computing defaults and maybeZ; below, we’ll unset
    // these constant colors back to undefined since they will instead be
    // populated by a channel generated by the initializer.
    const fillDensity = isDensity(fill) && ((fill = "currentColor"), true);
    const strokeDensity = isDensity(stroke) && ((stroke = "currentColor"), true);
    super(
      data,
      {
        x: {value: x, scale: "x", optional: true},
        y: {value: y, scale: "y", optional: true},
        z: {value: maybeZ({z, fill, stroke}), optional: true},
        weight: {value: weight, optional: true}
      },
      densityInitializer({...options, fill, stroke}, fillDensity, strokeDensity),
      defaults
    );
    if (fillDensity) (this as any).fill = undefined;
    if (strokeDensity) (this as any).stroke = undefined;
    this.z = z;
  }
  filter(index: any): any {
    return index; // don’t filter contours constructed by initializer
  }
  renderJSX(this: any, index: any, scales: any, channels: any): ReactNode {
    // A mark whose data is null has no index; render nothing rather than crash.
    if (index == null) index = [];
    const {contours} = channels;
    const path = geoPath();
    const indirect = indirectStyleProps(this);
    const transform = transformProp(this, {});
    const direct = directStyleProps(this);
    const paths = (index as number[]).map((i, k) => {
      const channel = channelStyleProps(i, channels);
      const titled = withTitleChild(this, channels, i, null);
      const pathEl = h("path", {key: k, ...direct, ...channel, d: path(contours[i]) ?? undefined}, titled);
      return withHrefWrap(channels, this.target, i, pathEl);
    });
    return h("g", {...indirect, ...transform}, paths);
  }
}

/**
 * Returns a mark that draws contours representing the estimated density of the
 * two-dimensional points given by **x** and **y**, and possibly weighted by
 * **weight**. If either **x** or **y** is not specified, it defaults to the
 * respective middle of the plot’s frame.
 *
 * If the **stroke** or **fill** is specified as *density*, a color channel is
 * constructed with values representing the density threshold value of each
 * contour.
 */
export function density(data?: Data, {x, y, ...options}: DensityOptions = {}): Density {
  [x, y] = maybeTuple(x, y);
  return new Density(data, {...options, x, y});
}

const dropChannels = new Set(["x", "y", "z", "weight"]);

function densityInitializer(options: any, fillDensity: any, strokeDensity: any) {
  const k = 100; // arbitrary scale factor for readability
  let {bandwidth, thresholds} = options;
  bandwidth = bandwidth === undefined ? 20 : +bandwidth;
  thresholds =
    thresholds === undefined
      ? 20
      : typeof thresholds?.[Symbol.iterator] === "function"
      ? coerceNumbers(thresholds)
      : +thresholds;
  return initializer(
    options,
    function (this: any, data: any, facets: any, channels: any, scales: any, dimensions: any, context: any) {
      const W = channels.weight ? coerceNumbers(channels.weight.value) : null;
      const Z = channels.z?.value;
      const {z} = this;
      const [cx, cy] = applyFrameAnchor(this, dimensions);
      const {width, height} = dimensions;

      // Get the (either scaled or projected) xy channels.
      const {x: X, y: Y} = applyPosition(channels, scales, context);

      // Group any of the input channels according to the first index associated
      // with each z-series or facet. Drop any channels not be needed for
      // rendering after the contours are computed.
      const newChannels: any = Object.fromEntries(
        Object.entries(channels)
          .filter(([key]) => !dropChannels.has(key))
          .map(([key, channel]: [string, any]) => [key, {...channel, value: []}])
      );

      // If the fill or stroke encodes density, construct new output channels.
      const FD: any = fillDensity && [];
      const SD: any = strokeDensity && [];

      const density: any = (contourDensity() as any)
        .x(X ? (i: any) => X[i] : cx)
        .y(Y ? (i: any) => Y[i] : cy)
        .weight(W ? (i: any) => W[i] : 1)
        .size([width, height])
        .bandwidth(bandwidth);

      // Compute the grid for each facet-series.
      const facetsContours: any[] = [];
      for (const facet of facets) {
        const facetContours: any[] = [];
        facetsContours.push(facetContours);
        for (const index of Z ? groupZ(facet, Z, z) : [facet]) {
          const contour = density.contours(index);
          facetContours.push([index, contour]);
        }
      }

      // If explicit thresholds were not specified, find the maximum density of
      // all grids and use this to compute thresholds.
      let T = thresholds;
      if (!(T instanceof TypedArray)) {
        let maxValue = 0;
        for (const facetContours of facetsContours) {
          for (const [, contour] of facetContours) {
            const max = contour.max;
            if (max > maxValue) maxValue = max;
          }
        }
        T = Float64Array.from({length: thresholds - 1}, (_, i) => (maxValue * k * (i + 1)) / thresholds);
      }

      // Generate contours for each facet-series.
      const newFacets: any[] = [];
      const contours: any[] = [];
      for (const facetContours of facetsContours) {
        const newFacet: any[] = [];
        newFacets.push(newFacet);
        for (const [index, contour] of facetContours) {
          for (const t of T) {
            newFacet.push(contours.length);
            contours.push(contour(t / k));
            if (FD) FD.push(t);
            if (SD) SD.push(t);
            for (const key in newChannels) {
              newChannels[key].value.push(channels[key].value[index[0]]);
            }
          }
        }
      }

      // If the fill or stroke encodes density, ensure that a zero value is
      // included so that the default color scale domain starts at zero. Otherwise
      // if the starting range value is the same as the background color, the
      // first contour might not be visible.
      if (FD) FD.push(0);
      if (SD) SD.push(0);

      return {
        data,
        facets: newFacets,
        channels: {
          ...newChannels,
          ...(FD && {fill: {value: FD, scale: "color"}}),
          ...(SD && {stroke: {value: SD, scale: "color"}}),
          contours: {value: contours}
        }
      };
    }
  );
}

function isDensity(value: any) {
  return /^density$/i.test(value);
}
